config/routes.rb
Rails.application.routes.draw do
  get 'bookings/destroy'
  get 'users/show'
  get 'pages/home'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'user', to: 'users#profile', as: :profile
  # resources :users, only: [ :show ] # I want to show the airplane listing/booking the user have when opening the user profile
  resources :airplanes do
    resources :bookings, only: [ :create ]
  end
  resources :bookings, only: [ :index, :show, :destroy] do
   resources :reviews, only: [ :create ]
 end
  # Reviews cannot be edited and will all be shown at the page when you want to reserve the plane with description, etc
  # what if I want to have two separate reviews? one from the host one from the guest
  # I added new route for booking destory and it wont work
end

app/models/airplane.rb
class Airplane < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  mount_uploader :photo, PhotoUploader
  geocoded_by :airport
  after_validation :geocode, if: :will_save_change_to_airport?
  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present? && !Airplane.near(params[:query], 1000).empty?
      @airplanes = Airplane.near(params[:query], 1000)
    else
      @airplanes = Airplane.geocoded
      @message = "There are no available planes in your area, please see other locations"
    end
      @markers = @airplanes.map do |airplane|
        {
          lat: airplane.latitude,
          lng: airplane.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { airplane: airplane })
        }
      end
  end

  def show
    set_airplane
    authorize @airplane
    @reviews = @airplane.reviews
    @booking = Booking.new
  end

  def new
    @airplane = Airplane.new
    authorize @airplane
    if user_signed_in?
      if current_user.present?
      else
        redirect_to new_user_registration_path
        flash[:alert] = 'Please sign up before booking'
      end
    else
      redirect_to user_session_path
      flash[:alert] = 'Please log in before booking'
    end
  end

  def create
    @airplane = Airplane.new(airplane_params)
    authorize @airplane
    @airplane.user = current_user
    if @airplane.save
      redirect_to airplane_path(@airplane), notice: "Your plane has been listed!"
    else
      render :new
    end
  end

  def edit
    set_airplane
    authorize @airplane
  end

  def update
    set_airplane
    authorize @airplane
    if @airplane.update(airplane_params)
      redirect_to airplane_path(@airplane)
    else
      render :edit
    end
  end

  def destroy
    set_airplane
    authorize @airplane
    @airplane.destroy
    redirect_to profile_path
  end

  private

  def set_airplane
    @airplane = Airplane.find(params[:id])
  end

  def airplane_params
    params.require(:airplane).permit(:airplane_id, :description, :airport, :price_per_day, :title, :photo)
  end
end

app/views/airplanes/_info_window.html.erb
<%= airplane.title %>

app/views/airplanes/create.html.erb
<h1>Airplanes#create</h1>
<p>Find me in app/views/airplanes/create.html.erb</p>

app/views/airplanes/destroy.html.erb
<h1>Airplanes#destroy</h1>
<p>Find me in app/views/airplanes/destroy.html.erb</p>

app/views/airplanes/edit.html.erb
<div class="container_login banner-flat" style="background-image: url('#');">
  <div class="form_card">
    <h1>Edit Listing</h1>
    <h2>What changes do you want to make?</h2>
    <%= simple_form_for (@airplane) do |f| %>
      <div class="col-xs-12 col-sm-4-offset-3">
      <%= f.input :title %>
      <%= f.input :price_per_day %>
      <%= f.input :description %>
      <%= f.input :airport %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/airplanes/index.html.erb
<div class="index-container text-center">
  <% if !Airplane.near(params[:query], 10).empty? %>
<h1>These are the available planes in your area:</h1>
<% else %>
<h3><%= @message %></h3>
<% end %>
<div class="container mb-5">
  <div class="row pb-5">
    <% @airplanes.each do |airplane| %>
      <div class="col-md-4 mb-3">
        <%= link_to airplane do %>
        <div class="card-trip">
          <% if airplane.photo.filename.nil? %>
            <img src="https://robbreportedit.files.wordpress.com/2018/05/pilatus-pc-24.jpg?w=1000" />
          <% else %>
            <%= cl_image_tag airplane.photo %>
          <% end %>
          <div class="card-trip-infos">
            <div>
              <h2><%= airplane.title %></h2>
              <h2><%= airplane.photo %></h2>
              <h2><%= airplane.airport %></h2>
            </div>
            <h2 class="card-trip-pricing">$<%= airplane.price_per_day %></h2>
          </div>
        </div>
      <% end %>
      </div>
    <% end %>
  </div>
</div>


<div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

app/views/airplanes/new.html.erb
<div class="listing-container">
  <div class="col-md-6 offset-md-3">
    <div class="listing-row">
    <h1 id="listing-title">Let's get started listing your Jet.</h1>
    <%= simple_form_for(@airplane) do |f|%>
    <div class="row-listing-form">
      <%= f.input :title %>
      <%= f.input :price_per_day %>
      <%= f.input :description %>
      <%= f.input :airport %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <div class="listing-submit-row">
      <%= f.button :submit, "List your Jet", class: "btn-listing" %>
      </div>
   </div>
  <% end %>
    </div>
  </div>
</div>

app/views/airplanes/show.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-md-6">
      <div class="card-trip text-center">
      <% if @airplane.photo.filename.nil? %>
        <img src="https://robbreportedit.files.wordpress.com/2018/05/pilatus-pc-24.jpg?w=1000" />
      <% else %>
        <%= cl_image_tag @airplane.photo %>
      <% end %>
      <div class="card-trip-infos">
        <div>
          <h1> <%= @airplane.title %></h1>
          <h2>Location: <%= @airplane.airport %></h2>
          <p>Description: <%= @airplane.description %></p>
          <h2>Reviews</h2>
          <% @reviews.each do |review| %>
         <p>rating: <%= review.rating %></p>
         <p>review: <%= review.content %></p>
         <% end  %>
         <h2><%= "$#{@airplane.price_per_day}" %></h2>
         <% if current_user == @airplane.user %>
          <%= link_to "Edit listing", edit_airplane_path %>
          <%= link_to "Remove listing", airplane_path, method: :delete, data: { confirm: 'Are you sure you want to remove this listing?'} %>
          <%= link_to "Back to profile", profile_path %>
          <% else %>
          <%= link_to "Back to profile", profile_path %>
          <% end %>
        </div>
    </div>
    </div>
  </div>
  <% if user_signed_in? && @airplane.user_id != current_user.id %>
  <div id='airplane-booking-dates' data-unavailable="<%= @airplane.unavailable_dates.to_json %>">
    <% if current_user.id != @airplane.user_id  %>
       <%= simple_form_for([@airplane, @booking]) do |f| %>
           <%= f.input :start_date, as: :string, type: :text %>
           <%= f.input :end_date, as: :string, type: :text %>
           <%= f.input :arrival, as: :string, type: :text, input_html: {id: "search-airport2"}  %>
           <%= f.submit "Book", class: "btn btn-primary" %>
        <% end %>
    <% end %>
 </div>
  <% else %>
  <% end %>
  </div>
</div>

app/views/airplanes/update.html.erb
<h1>Airplanes#update</h1>
<p>Find me in app/views/airplanes/update.html.erb</p>