config/routes.rb
Rails.application.routes.draw do
  get 'bookings/destroy'
  get 'users/show'
  get 'pages/home'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'user', to: 'users#profile', as: :profile
  # resources :users, only: [ :show ] # I want to show the airplane listing/booking the user have when opening the user profile
  resources :airplanes do
    resources :bookings, only: [ :create ]
  end
  resources :bookings, only: [ :index, :show, :destroy] do
   resources :reviews, only: [ :create ]
 end
  # Reviews cannot be edited and will all be shown at the page when you want to reserve the plane with description, etc
  # what if I want to have two separate reviews? one from the host one from the guest
  # I added new route for booking destory and it wont work
end

app/views/shared/_banner.html.erb
<%= video_tag 'homepage.mp4', class:"home-video", autoplay:true, muted:true, loop:true %>
  <div class="container">
    <h1>Rent a Jet</h1>
    <p>Fly private anywhere around the world.</p>
    <form class="d-flex justify-content-center mt-5 flex-column w-50 mx-auto" action="/airplanes">
      <div class="d-flex justify-content-center">
        <div class="form-group w-100 mr-6">
          <label for="departure-city" style="color: white;">Departure City</label>
          <input type="text" name="query" class="form-control" id="search-airport" placeholder="From">
        </div>
      </div>

      <div class="d-flex justify-content-center">
        <div class="form-group w-50 mr-5">
          <label for="departure" style="color: white;">Choose date</label>
          <input type="text" readonly="readonly" name="start_date" class="form-control" id="depart">
        </div>
        <div class="form-group w-50">
          <label for="arrival" style="color: white;">Choose date</label>
          <input type="text" readonly="readonly" name="end_date" class="form-control" id="arrival">

        </div>
      </div>
      <button type="submit" id="submit-button" class="btn btn-dark d-flex justify-content-center mx-auto">Search Jets</button>
    </form>
  </div>

app/views/shared/_card.html.erb
<!-- <div class="container-product">
<div class="card-product">
  <img src="https://www.aopa.org/-/media/images/aopa-main/news-and-media/2019/july/0701_c210.jpg" />
  <div class="card-product-infos">
    <h2>Cesna</h2>
    <p>Small personal plane, perfect for short trips & small groups.</p>
  </div>
</div>
<div class="card-product">
  <img src="https://g.foolcdn.com/editorial/images/168693/f-16.jpg" />
  <div class="card-product-infos">
    <h2>Fighter jet</h2>
    <p>Perfect for dogfights & air to air combat</p>
  </div>
</div>
<div class="card-product">
  <img src="https://cdn.topmiles.com/images/mytrip/2017/Gulfstream-5-Private-Jet/68.jpg" />
  <div class="card-product-infos">
    <h2>G5</h2>
    <p>Release your inner billionare</p>
  </div>
</div>
<div class="card-product">
  <img src="https://upload.wikimedia.org/wikipedia/commons/e/ec/B-2_Spirit_%28cropped%29.jpg" />
  <div class="card-product-infos">
    <h2>Steath bomber</h2>
    <p>Bomb people all over the world and never be seen</p>
  </div>
</div>
</div>
 -->

app/views/shared/_dateform.html.erb
<!-- # <%#= simple_form_for :search, url: root_path, method: :get do |f| %>
#   <div class="search-form-control form-group mx-auto">
#     <input class="form-control string required" type="date" name="search[query]" id="search_query" />
#     <button name="button" type="submit" class="btn btn-flat">
#       <i class="fas fa-search"></i> Search
#     </button>
#   </div>
# <#% end %>

 -->

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="#">
    <img src="https://cdn.clipart.email/b0190b693e6cd59a93271bfb976a0c33_white-clipart-aeroplane-pencil-and-in-color-white-clipart-aeroplane_300-204.png" />
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if user_signed_in? %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Home", pages_home_path, class: "nav-link #{params[:action] == 'home' ? 'active' : nil}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Rent your Jet", new_airplane_path, class: "nav-link #{params[:action] == 'new' ? 'active' : nil}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Trips", bookings_path, class: "nav-link #{params[:action] == 'index' ? 'active' : nil}" %>
        </li>
        <li class="nav-item dropdown">
          <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_640.png" />
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", profile_path, class: "dropdown-item" %>
            <%= link_to "Sign out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
          </div>
        </li>
      </ul>
    <% else %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Home", pages_home_path, class: "nav-link #{params[:action] == 'home' ? 'active' : nil}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link #{params[:action] == 'new' && params[:controller] == 'devise/registrations' ? 'active' : nil}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log in", user_session_path, class: "nav-link #{params[:action] == 'new' && params[:controller] == 'devise/sessions' ? 'active' : nil}" %>
        </li>
      </ul>
    <% end %>
  </div>
</div>

app/views/shared/_searchform.html.erb
<%= form_tag airplanes_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Where would you like to fly to?"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>